name: pull-request-checks

on:
  pull_request:
    branches: [ master ]

jobs:
  # Build .apk to check
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Gradle Assemble
      run: ./gradlew :library:assembleDebug --build-cache --no-daemon --stacktrace

  # Executes checks (unit tests, linter and etc.)
  checks:
    name: Checks
    needs: assemble
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Execute check with Gradle
        run: ./gradlew :library:testDebug --build-cache --no-daemon --stacktrace

      - name: Zip test reports
        run: find . -type d -regex ".*/build/reports/tests/.*DebugUnitTest" -exec zip -r reports.zip {} +

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-reports
          path: reports.zip

  # Runs instrumentation tests
  instrumentation-tests:
    name: Instrumentation tests
    needs: assemble
    runs-on: macos-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        api-level:
          - 21
          - 23
          - 24
          - 29

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew :library:connectedDebugAndroidTest --build-cache --no-daemon --stacktrace

      - name: Upload tests reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: 'android-tests-${{ matrix.api-level }}-reports'
          path: library/build/reports/androidTests

  # Runs screenshot tests
  screenshot-tests:
    name: Screenshot tests
    needs: assemble
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Screenshot Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          arch: x86_64
          script: ./gradlew :library:executeScreenshotTests --build-cache --no-daemon --stacktrace

      - name: Upload tests reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: 'screenshot-tests-reports'
          path: library/build/reports/shot
